services:
    maxs94.geoname.import.timezone:
        class: Maxs94\Bundle\GeoNameBundle\Import\TimeZoneImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    maxs94.geoname.import.administrative:
        class: Maxs94\Bundle\GeoNameBundle\Import\AdministrativeImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    maxs94.geoname.import.geoname:
        class: Maxs94\Bundle\GeoNameBundle\Import\GeoNameImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true


    maxs94.geoname.import.country:
        class: Maxs94\Bundle\GeoNameBundle\Import\CountryImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    maxs94.geoname.import.hierarchy:
        class: Maxs94\Bundle\GeoNameBundle\Import\HierarchyImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true


    #auto register all commands
    maxs94.geoname.command.import:
        class: Maxs94\Bundle\GeoNameBundle\Command\ImportCommand
        tags:
              - { name: console.command }