<?php

namespace Maxs94\Bundle\GeoNameBundle\Repository;

/**
 * AdministrativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrativeRepository extends \Doctrine\ORM\EntityRepository
{
}
